hidden_dims: 4 # currently equal to the input size
input_size: 4
epochs: 80
lr: 1e-3
# noise_factor: 0
# dataset: spa  # spa / rus
grad_clipping: 0.7

model: crnn  # attention_gru, gru, crnn, attention_crnn